"""汉字模块仓储接口（级别 / 字条 / 学习进度）。"""

from __future__ import annotations

from typing import Protocol

from app.domain.models.hanzi import HanziCharacter, HanziLevel, HanziUserProgress


class HanziLevelRepository(Protocol):
    async def list_all(self) -> list[HanziLevel]: ...

    async def find_by_id(self, id_: str) -> HanziLevel | None: ...

    async def find_by_name(self, name: str) -> HanziLevel | None: ...

    def add(self, entity: HanziLevel) -> None: ...

    async def delete(self, entity: HanziLevel) -> None: ...


class HanziCharacterRepository(Protocol):
    async def list_by_level(self, level_id: str) -> list[HanziCharacter]: ...

    async def find_by_id(self, id_: str) -> HanziCharacter | None: ...

    async def find_by_char(self, char: str) -> HanziCharacter | None: ...

    async def existing_chars(self, chars: list[str]) -> set[str]: ...

    async def count_by_level(self, level_id: str) -> int: ...

    async def count_by_levels(self, level_ids: list[str]) -> dict[str, int]: ...

    async def max_order_index(self, level_id: str) -> int: ...

    def add(self, entity: HanziCharacter) -> None: ...

    def add_many(self, characters: list[HanziCharacter]) -> None: ...

    async def delete(self, entity: HanziCharacter) -> None: ...


class HanziProgressRepository(Protocol):
    async def find(self, user_id: str, character_id: str) -> HanziUserProgress | None: ...

    async def learned_ids_by_level(self, user_id: str, level_id: str) -> set[str]: ...

    async def progress_map_by_level(
        self, user_id: str, level_id: str
    ) -> dict[str, HanziUserProgress]: ...

    async def learned_count_by_levels(
        self, user_id: str, level_ids: list[str]
    ) -> dict[str, int]: ...

    def add(self, entity: HanziUserProgress) -> None: ...

    async def delete(self, entity: HanziUserProgress) -> None: ...
