"""文生图模块仓储接口（模板 / 任务 / 图片 / 图片二进制）。"""

from __future__ import annotations

from typing import Protocol

from app.domain.models.t2i import T2IImage, T2IImageBlob, T2ITask, T2ITemplate


class T2ITemplateRepository(Protocol):
    async def find_by_id(self, id_: str) -> T2ITemplate | None: ...

    async def find_by_code(self, code: str) -> T2ITemplate | None: ...

    async def list_all(self) -> list[T2ITemplate]: ...

    def add(self, entity: T2ITemplate) -> None: ...

    async def delete(self, entity: T2ITemplate) -> None: ...


class T2ITaskRepository(Protocol):
    async def find_by_id(self, id_: str) -> T2ITask | None: ...

    async def find_by_hash(self, keywords_hash: str) -> T2ITask | None: ...

    async def count_by_template_code(self, template_code: str) -> int: ...

    async def list_by_template(
        self, template_code: str, page: int, page_size: int
    ) -> tuple[list[T2ITask], int]: ...

    def add(self, entity: T2ITask) -> None: ...


class T2IImageRepository(Protocol):
    async def find_by_id(self, id_: str) -> T2IImage | None: ...

    async def list_by_task(self, task_id: str) -> list[T2IImage]: ...

    async def has_generating(self, task_id: str) -> bool: ...

    def add(self, entity: T2IImage) -> None: ...

    async def delete(self, entity: T2IImage) -> None: ...


class T2IImageBlobRepository(Protocol):
    async def get_bytes(self, image_id: str) -> tuple[bytes, str | None] | None: ...

    def add(self, entity: T2IImageBlob) -> None: ...

    async def delete_by_image(self, image_id: str) -> None: ...
